services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/teebay
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/teebay/client
    depends_on:
      - web

